# Generated by Django 5.0.2 on 2024-03-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('kode_mk', models.CharField(max_length=20)),
                ('nama_mk', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('kelas', models.CharField(max_length=10)),
                ('jadwal', models.DateTimeField()),
                ('pengajar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuangPercobaan',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('gedung', models.CharField(max_length=100)),
                ('lantai', models.IntegerField()),
                ('ket', models.TextField()),
                ('svg', models.ImageField(upload_to='svg/')),
                ('id_jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.jadwal')),
            ],
        ),
    ]
